language: go

go: 1.12.x

services:
  - docker

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled
    IMAGE=quay.io/schjan/fritzdect-exporter

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) test"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install: true

script:
  - GO111MODULE=on go test -v -bench=. -cover -benchmem -race  ./...

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod